steps:
- name: 'ubuntu'
  script: |
    #!/usr/bin/env bash
    if [[ -z "$BRANCH_NAME" ]]; then
      echo "BRANCH_NAME is empty"
      exit 1
    else
      echo "We are on branch: $BRANCH_NAME"
    fi
    
    echo "Your project ID is $PROJECT_ID"
substitutions:
  _BRANCH_NAME: NONE # Default value
options:
  automapSubstitutions: true
